services:
  # Backend API Service
  - type: web
    name: space-station-cargo-api
    env: python
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: sqlite:///space_station_cargo.db
      - key: DEBUG
        value: "0"

  # Frontend Static Site
  - type: web
    name: space-station-cargo-frontend
    env: static
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_VERSION
        value: 18
